name: Build and Deploy APK

on:
  push:
    branches:
      - main  # Csak akkor fut le, ha a 'main' ágra történik push
  pull_request:
    branches:
      - main  # Csak akkor fut le, ha a 'main' ágra történik pull request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer
        buildozer init

    - name: Build Android APK
      run: buildozer -v android debug

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: app
        path: ./bin
