name: Build Android App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y portaudio19-dev

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # Choose an available Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build PyAudio from source
      run: |
        git clone --depth 1 --branch v0.2.15 https://github.com/jleb/pyaudio.git
        cd pyaudio
        python setup.py install

    - name: Build with Buildozer
      run: |
        sudo apt-get install -y \
          libportmidi-dev \
          libswscale-dev \
          libavformat-dev \
          libavcodec-dev \
          libsdl2-dev
        buildozer -v android debug

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: package
        path: ./bin/
